### ISSUE TITLE
能否详细说明一下proxy的使用方法

### ISSUE THREAD

**Issue by duansix** [MagicalMadoka/openai-signup-tool#2]
通过https://github.com/FynnFbc/TunnelProxyPool自建了IP地址
填写如下配置：
"proxy": "http://123.123.123.123:8080/get?type=HTTP&count=10&anonymity=all",

然后日志报错：
`2024-01-03 03:03:08.015 | WARNING  | signup:_try_solve_arkose_challenge:340 - fail to resolve arkose challenge current retry num 0
2024-01-03 03:03:31.669 | INFO     | signup:_try_solve_arkose_challenge:268 - game type: 4, que: Using the arrows, move the person to the indicated seat., num: 3
Traceback (most recent call last):
  File "/app/signup.py", line 297, in _try_solve_arkose_challenge
    index = self._get_ans_index(que, base64)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/signup.py", line 163, in _get_ans_index
    index = resp.json()['solution']['objects'][0]
            ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'solution'
2024-01-03 03:03:32.008 | WARNING  | signup:_try_solve_arkose_challenge:340 - fail to resolve arkose challenge current retry num 0
2024-01-03 03:03:55.640 | INFO     | signup:_try_solve_arkose_challenge:268 - game type: 4, que: Using the arrows, move the person to the indicated seat., num: 3
Traceback (most recent call last):
  File "/app/signup.py", line 297, in _try_solve_arkose_challenge
    index = self._get_ans_index(que, base64)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/signup.py", line 163, in _get_ans_index
    index = resp.json()['solution']['objects'][0]
            ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'solution'
2024-01-03 03:03:55.998 | WARNING  | signup:_try_solve_arkose_challenge:340 - fail to resolve arkose challenge current retry num 0
2024-01-03 03:04:05.058 | WARNING  | signup:_save_account:222 - JldXjYzXqeQDDQ0@locmail.cc sess found fail
2024-01-03 03:04:16.216 | ERROR    | signup:sign_up:40 - error in signup: Too many signups from the same IP
2024-01-03 03:04:16.326 | ERROR    | pool_manager:_worker:31 - An error occurred: Too many signups from the same IP
Traceback (most recent call last):
  File "/app/main.py", line 31, in <module>
    main()
  File "/app/main.py", line 27, in main
    raise GlobalState.exception
  File "/app/pool_manager.py", line 29, in _worker
    func(*args, **kwargs)
  File "/app/main.py", line 23, in signup
    s.sign_up()
  File "/app/signup.py", line 41, in sign_up
    raise e
  File "/app/signup.py", line 38, in sign_up
    func_timeout(5 * 60, self._sign_up)
  File "/usr/local/lib/python3.11/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/usr/local/lib/python3.11/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/app/signup.py", line 83, in _sign_up
    raise GlobalState.exception
signup.Interrupted: Too many signups from the same IP
2024-01-03 03:04:27.285 | ERROR    | signup:sign_up:40 - error in signup: Too many signups from the same IP
2024-01-03 03:04:27.401 | ERROR    | pool_manager:_worker:31 - An error occurred: Too many signups from the same IP
2024-01-03 03:04:38.279 | ERROR    | signup:sign_up:40 - error in signup: Too many signups from the same IP
2024-01-03 03:04:38.395 | ERROR    | pool_manager:_worker:31 - An error occurred: Too many signups from the same IP
`

**Comment by MagicalMadoka** [comment]
http://user:password@123.45.67.89:8080

正常的URL格式，没密码可以省略前面。
