### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'data/account.txt'

### ISSUE THREAD

**Issue by duansix** [MagicalMadoka/openai-signup-tool#8]
一直无法写入文件 不清楚什么原因 已经手动删除account.txt和sess.txt文件了 它自己无法创建这个文件 给了父目录data777权限也不行

2024-01-04 00:47:24.115 | INFO | signup:_try_solve_arkose_challenge:268 - game type: 4, que: Use the arrows to move the train to the coordinates indicated in the left image, num: 6
2024-01-04 00:48:02.423 | DEBUG | signup:_try_solve_arkose_challenge:336 - no try again button found may be resolved
Traceback (most recent call last):
File "/app/signup.py", line 38, in sign_up
func_timeout(5 * 60, self._sign_up)
File "/usr/local/lib/python3.11/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
raise_exception(exception)
File "/usr/local/lib/python3.11/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
raise exception[0] from None
File "/app/signup.py", line 114, in _sign_up
self._save_account(email, password)
File "/app/signup.py", line 203, in _save_account
sess = self._save_and_get_sess(email, password)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/signup.py", line 179, in _save_and_get_sess
with open("data/account.txt", "a", encoding="utf-8") as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'data/account.txt'

**Comment by MagicalMadoka** [comment]
你是在linux上用root跑的？ 还是别的用户跑的。系统发一下

**Comment by duansix** [comment]
已解决
